### ISSUE TITLE
User Story: Search Function

### ISSUE THREAD

**Issue by hamedbahrami479** [hamedbahrami479/CapStone#4]
**_Title_**: Search Functionality

**_Value Proposition_**: As a user I want to have the opportunity to receive valuable knowledge on how to proceed with my waste in order to handle in the most educated and efficient way. For example: I am holding a piece of laminated paper in my hand and would intuitively put it into the blue waste bin, although it needs to be put into the black waste bin due to the special coating. Therefore the basic function should enable a search functionality with an integrated drop down list to choose from.

**_Description_**:

<img width="465" alt="Bildschirmfoto 2022-05-04 um 11 36 23" src="https://user-images.githubusercontent.com/100590440/166658136-17c94940-5103-44fc-ae4f-5c647dfb405f.png">

**_Acceptance Criteria_**:

- The GIB Text is shown  in the prototype
- The drop down area is in place with a list of products respectively Product groups to choose from
- Choosing one of the products from the drop down, will later on send an answer back into the "result popping up" box (in scope of user story 2) 
- A couple of options to be chosen from the drop down
- Every drop down option has to send a result back. No result is o option.

**_Tasks_**: 

- [x] Define Styles in Figma
- [x] Define a senseful sample of product groups. Not more than 10
- [x] Create a side branch and work in this branch
- [x] Create a Header with comfort green color in the background and the GIB text
- [x] Create a body with comfort blue color in the background 
- [x] Create a textfield, where the Question "What would you like....?" will occur
- [x] Create a search field, from which the user is able to choose out of the 10 (max) data samples
- [x] Create a result box, where the search result with the handling suggestion is displayed
- [x] Write your test script

**Comment by PReichetanz** [comment]
You are almost there!

Just a few things to consider:

- Please rewrite the value proposition as suggested "As a user...etc.).
- I would remove the header, but that's up to you.
- Acceptance criteria #3 seems not to be complete
- Tasks: You don't need to write down that you need a separate branch, Pull Request and merge

**Comment by hamedbahrami479** [comment]
done

**Comment by hamedbahrami479** [comment]
done
